# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2c73c8d702cbcb7bc68032dd2860c2dfbe1729036690f3aa865cfb672ef1125c59cc85ebe6b927131a7e27fc67b0871e7ac1e061ebe4fd6cf158cf7b07e1e1b

test:
  secret_key_base: 58b1d129841dc41bb9ab9c193c4404a16fbeb955a8f0ecaa2665651515291379fe7ecadeffb738886013043e6146bfed021108564908b0c97301051f73690dac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
